# Generated by Django 3.2 on 2021-04-22 06:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audiobook',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=100)),
                ('Author', models.CharField(max_length=100)),
                ('Narrator', models.CharField(max_length=100)),
                ('Audiobook_Duration', models.PositiveIntegerField()),
                ('Upload_Time', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=1000)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Podcast_Name', models.CharField(max_length=100)),
                ('Podcast_Duration', models.PositiveIntegerField()),
                ('Upload_Time', models.DateTimeField(auto_now_add=True)),
                ('Host', models.CharField(max_length=100)),
                ('Participants', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=10)),
                ('created_by', models.CharField(max_length=1000)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Song_Duration', models.PositiveIntegerField()),
                ('Upload_Time', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=1000)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
